package examples.restApiTests;

import com.github.javafaker.Faker;
import io.restassured.RestAssured;
import org.testng.annotations.Test;


import static java.lang.String.format;

public class RestAssuredTest {

    private String name = Faker.instance().name().username();
    private String email = Faker.instance().internet().emailAddress();
    private String token = System.getenv("TOKEN"); // your token generated by service GOREST (https://gorest.co.in/my-account/access-tokens)

    private String payload = format(
            "{\"name\":\"%s\"," +
                    "\"email\":\"%s\"," +
                    "\"gender\":\"male\"," +
                    "\"status\":\"active\"}", name, email);

    @Test
    public void testPost() {
        int userId = RestAssured.given()
                .baseUri("https://gorest.co.in")
                .header("content-type", "application/json")
                .header("Authorization", format("Bearer %s", token))
                .body(payload)
                .log().ifValidationFails()
                .post("/public/v2/users")
                .then()
                .assertThat()
                .statusCode(201)
                .extract().body().jsonPath().get("id");
    }

}
